version: '3.4'
services:
  pwserver:
    build: .
    container_name: pwserver
    volumes:
      - ./serverfiles:/home/pwserver/serverfiles
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    restart: unless-stopped